### ISSUE TITLE
Repo setup fails on Ubuntu

### ISSUE THREAD

**Issue by Cornellio** [basho-labs/puppet-riak#65]
The apt package installation fails on Ubuntu because the module is setting package source to Debian instead of Ubuntu.

The source list at `/etc/apt/sources.list.d/riak.list` needs to be set as:

    deb https://packagecloud.io/basho/riak/ubuntu/ precise main
    deb-src https://packagecloud.io/basho/riak/ubuntu/ precise main

Instead of this:

    deb https://packagecloud.io/basho/riak/debian/ precise main
    deb-src https://packagecloud.io/basho/riak/debian/ precise main

**Comment by GabrielNicolasAvellaneda** [comment]
@Cornellio this pull request solves the problem:
https://github.com/basho-labs/puppet-riak/pull/70

Please note that in my Ubuntu box I needed to install using the following parameters:

```
  class { '::riak':
    version => 'latest', # default, use a package version if desired
    # settings in the settings hash are written directly to settings.conf.
    settings => {
      'nodename' => 'riak@127.0.0.1'
    },
  }
```

Because the following default didn't worked for me:
https://github.com/basho-labs/puppet-riak/blob/master/manifests/params.pp#L38

**Comment by Cornellio** [comment]
Thank you @GabrielNicolasAvellaneda and will await the merge into upstream.
